security:
    password_hashers:
        App\Entity\Seller:
            algorithm: auto

    providers:
        seller_provider:
            entity:
                class: App\Entity\Seller
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/v1/login
            stateless: true
            json_login:
                check_path: /api/v1/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/v1/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/register, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_SELLER }